### ISSUE TITLE
Nested child element not showing for concurrent events

### ISSUE THREAD

**Issue by doofin** [raquo/Laminar#11]
```scala
val tp=new EventBus[Unit]()
        
div(button("click",(onClick() mapTo(()))-->tp ),
          child<--(tp.$ mapTo div("clicked1", child <-- (tp.$ mapTo (div("clicked2")))))
        )
```

clicked1 is shown but not clicked2,I guess maybe div("clicked2") needs some delay?

**Comment by raquo** [comment]
The short answer is that this is probably what you want instead:

```
div(
  button("click", (onClick() mapTo(()))-->tp ),
  div(
    child.text <-- tp.$.mapTo("clicked1"),
    div(child.text <-- (tp.$ mapTo "clicked2"))
  )
```

(I did not run this, so please forgive any typos)

Now, here is why this works and your version doesn't:

When your version of the code is run, a div with a button is created. Nothing else is created until tp.$ fires because `child <--` needs to wait for an event in order to render anything.

Then, when tp.$ fires, a div is created with text "clicked1" in it. For pretty much the same reason that this div wasn't created until tp.$ was fired, `div("clicked2")` will not be created until tp.$ is fired the second time. Well, except that `div("clicked2")` will (probably) never be created because when tp.$ fires next, the current `div("clicked1", ...)` will be discarded and replaced with a new div, because that's what the outer child <-- does.

---

I will keep this issue open because I think regardless of everything I said, there might be a streaming library issue here. I have a hunch that it's both possible and desirable for a streaming library to handle this case, so I might try to do that in Airstream. Thanks for bringing it up.

---

PS unrelatedly, you don't need to do `(onClick() mapTo(()))-->tp`. If you define tp to be `new EventBus[dom.MouseEvent]()` instead, you can just say `onClick --> tp` which is much shorter, and more efficient.

**Comment by doofin** [comment]
I have circumvented this issue by filtering out the event for patent element update

**Comment by raquo** [comment]
Yep saw that XStream issue, will look into it in the coming days.

Delay is not a very good way to solve this, as it introduces visual glitches.

Try using `tp.$.remember()` instead of tp.$ – see XSream.js documentation on what it does. Basically, it creates a MemoryStream that will emit its last value immediately on subscription. It will probably work for your case, just make sure to define `val tpm = tp.$.remember()` next to `val tp`, not inside the mapped stream (or it will suffer the same problem as your original solution – will be re-created on every new event, so nothing will be remembered)

**Comment by raquo** [comment]
Just added a test verifying that the next version of Laminar (developed in #8) fixes the original issue filed here despite this not being the intended usage.

**Comment by doofin** [comment]
Thanks! Happy Chinese New Year!
