### ISSUE TITLE
Laminar is a Scala.js reactive library [SEO]

### ISSUE THREAD

**Issue by asdf8dfafjk** [raquo/Laminar#122]
It's not always ethical but seeing as you are a "reactive toolkit" but you don't appear on the first page searching for `scala.js reactive library` or `scala.js reactive toolkit`, a bit of SEO might help.

How about: 

`Native Scala.js library for building reactive user interfaces` ?

**Comment by raquo** [comment]
Ok I've updated the issue title so that our search gods know that Laminar is a [scala.js reactive library](laminar.dev/). In fact, you could say it's not just a Scala.js reactive library, but subjectively one of the finest scala.js reactive libraries. Scala.js surprisingly has more than its fair number of reactive libraries, but some of them are abandoned and unmaintained. Laminar is a popular reactive library in the Scala.js world.

Goddamit I can't do this anymore, that will have to be enough. :D

On a serious note, I think Laminar does not come up for those search terms because people don't often talk about this kind of library as "reactive library", but rather more often they call it a "frontend library", "frontend framework". As you see most other frontend UI libraries don't come up either for your search query. In fact if you google "javascript reactive library", Laminar's most prominent Javascript alternatives such as React don't come up either. Actually, I spent a couple minutes and couldn't come up with a short name-agnostic query that would give me React's website as the first result. Closest I came was with "javascript frontend library" which had React's website at #7. Everything else is just listicle spam from various websites I've never heard of. I think this says more about the current state of google search than anything else, really.

Fortunately Laminar users tend to be very vocal about our library, various people have been mentioning it in basically every discussion of Scala frontend tools that I've seen. I'm grateful for the enthusiasm – word of mouth is what really counts, long term, I think, especially now that all our "words" are recorded online for any competent search engine to pick up on.
