### ISSUE TITLE
Easy `Var`: Providing implicit conversion from `Var[A]` into `Source[String]` ?

### ISSUE THREAD

**Issue by windymelt** [raquo/Laminar#159]
Hi, this is an idea for providing implicit conversion for `Var`.

As we know, `Var` is very fundamental element in Laminar. Both beginner and expert will use `Var`.

My problem is: 

- I have to convert `Var[A]` with `value <-- fooVar.signal.map(_.toString)` every time.
- But almost all Scala object can be converted into `String` using `.toString` (e.g. `Int`, `Double`).

If we provide implicit conversion from `Var[A]` into `Source[String]`, we can write stream much more intuitively in less code:

```
val fooVar = Var(42) // => Var[Int]
...
value <-- fooVar // we can use it like Var[String]
```

**Comment by raquo** [comment]
> I think that's what Renderable is for?

Almost – `Renderable` is for rendering text inside HTML elements, it does not apply to attributes, including `value`, because when you set attributes, you typically provide values that will be read by the computer (and so they need to be precise, without automatic conversions), whereas outputting text to HTML is purely visual, and so for that purpose we can afford to loosen type safety a bit for the sake of convenience.

> provide implicit conversion from Var[A] into Source[String]

This would essentially create an implicit conversion of `A` to `String` (albeit only in the context of observables) – but Laminar owns neither the `A` type nor the `String` type, so we can't possibly in good faith have such an implicit conversion. Its behavior would be too broad and unpredictable, silently allowing code that users may legitimately expect to not compile.

If you want to enable `value <-- sourceOfAnything` syntax in your own code, you can create a new `<--` extension method for `HtmlProp[String, String]` that calls into the existing `<--` method and calls `.toObservable.map(_.toString)` like you mentioned. See [here](https://github.com/raquo/Laminar/blob/2ca18da3d8f66daf850af820746fef933ba0c2f9/src/main/scala/com/raquo/laminar/keys/HtmlProp.scala#L36). It's your choice whether to do this in your own code, but such an API is too loosely typed to be added to the library.

**Comment by raquo** [comment]
Closing because I don't think we can do this (see previous comment for reasons). If you want to discuss this further or have questions, feel free to post here or in Laminar Discord.
