### ISSUE TITLE
Q: Is it possible to use redux-style state management?

### ISSUE THREAD

**Issue by nartamonov** [raquo/Laminar#18]
I'm curious is it possible with Laminar to have whole app state in one big immutable object, like in Redux or ClojureScript's [re-frame](https://github.com/Day8/re-frame)?

For example, I have something like:

```scala
case class Todo(...)
case class User(...)
case class AppState(user: User, todos: Seq[Todo])
```

As far as I can understand to build view layer for this app-state we need something like (sorry, don't know well Laminar API, so I use pseudo-code):

```scala
def appView(state: ReactiveStream[State]): ReactiveNode[Div] = {
  // .. here we call child components userView(user: ReactiveStream[User])
  //    and todoView(todo: ReactiveStream[Todo]) ...
}
```

Does it have any sense? If not, **what's the recommended way to manage state with event-stream based frameworks?**

Btw, thanks for your great work! No doubts we need Scala-"native" solutions to cope with UI issues and I found Laminar and Outwatch very promising! :+1:

**Comment by raquo** [comment]
Hi,

First of all, Laminar docs in master are currently out of date. I will update them in the coming days. The code is v0.3-SNAPSHOT, whereas the docs are for v0.2. Lots of changes since then, but most notably we now use [Airstream](https://github.com/raquo/Airstream) instead of XStream.js

Airstream has first class support not only for streams, but also for State and Signal-s. You should read Airstream docs (that _are_ in fact up to date) about important differences between State and Signal.

You can imitate redux by having an instance of Var (State) while passing down things like `centralVar.map(_.user).toSignal` for reading and `centralVar.writer.map(newUser => centralVar.now().copy(user = newUser))` for updating. I might be off with the writer.map syntax a bit – see Airstream docs if this doesn't work.

However, I'm not sure if I would recommend that. If you have a global user variable that you need to read / write, you can just define it somewhere as a separate `Var` and pass its signal to components that need it. And if you have some state that is local to your component, just define it inside of your component. For example, while `user` might need to be global because it's used from multiple unrelated components, you might want to contain `todos` to the one component that uses that data instead of making it global, assuming you don't need to share between multiple unrelated components.

The big idea in Laminar is to use simple language-level (and general FRP) solutions instead of frameworks.

But do take all this with a grain of salt as I myself didn't have a chance to write a lot of Laminar code yet, and it's pretty flexible so multiple approaches are possible. You might want to check out https://github.com/raquo/laminar-examples, it is currently the only public Laminar code. It uses v0.3-SNAPSHOT so you can use it as a (lame) reference.

**Comment by nartamonov** [comment]
Thank you for the explanation, I'll check [laminar-examples](https://github.com/raquo/laminar-examples).

Regarding `centralVar`, does it mean that every update of a nested object inside `centralVar` will follow to re-rendering the whole DOM tree? For example, if I update user name, will todo list be re-rendered?

**Comment by raquo** [comment]
No, normally extraneous re-renders are not needed at all. In your code you will have code like `something <-- someSignal`. That means that when `someSignal` emits a new value, `something` will be updated in the DOM, nothing more.

In your user component you will probably have something like `div(child.text <-- `usernameSignal`)` where `usernameSignal` is derived from `centralVar`.  So when `usernameSignal` updates, a new DOM text node will be created and inserted into that div instead of the previous text node.

I assume nothing in the todo list depends on the username, so its DOM will not be touched at all when it updates.

The thing to **avoid** in Laminar is this pattern: `div(child <-- usernameSignal.map(username => span(username)))`. In that case, a new span element will be created every time usernameSignal updates. That is not a big deal in my contrived example because username updates are probably very rare, and this span is just one element, but if it was a bigger component and/or the updates were coming in more often that would be really inefficient.

---

Importantly, Airstream's State does not emit a new value if it is equal to its previous value. So you should make your components depend on individual chunks of `centralVar` (e.g. `centralVar.user`) rather than on the `centralVar` itself, because the value of `centralVar` itself will change with every update to any of `centralVar`'s contents because of immutability, but the individual chunks will only change when they themselves (or their children) change.

Note that Signal-s don't have the same de-duplication behaviour built-in. I wasn't sure about that, and I might add it later. For now you'll need to .map `centralVar` first to narrow it down, and only then convert it to a Signal, otherwise you'll get more DOM updates than needed.

**Comment by nartamonov** [comment]
> Importantly, Airstream's State does not emit a new value if it is equal to its previous value.

Cool, it's clear now! And what about sequences: if I add one more todo to the rather big list of todos, does it exist some way to effectively re-render DOM nodes for the list? If I understand correctly, [in such cases](https://github.com/OlivierBlanvillain/monadic-html/issues/13) we need virtual DOM as an optimisation technique, doesn't we?

**Comment by raquo** [comment]
Just released v0.3 together with documentation explaining the children stuff.

I'll keep this issue open because I want to document the centralized state management pattern eventually.

**Comment by raquo** [comment]
Similar question and answer about Diode: https://gitter.im/Laminar_/Lobby?at=5c54ea70f04ef00644c52a21

> I am curious if it is practical to use Laminar with Diode? I have an app with an existing (largish) diode model that I would love to try to implement with Laminar instead of one of the many React.js wrappers out there.

**Comment by raquo** [comment]
State management is now sufficiently documented under `Var` in Airstream docs I think.
