### ISSUE TITLE
Scala 2.13.0 support

### ISSUE THREAD

**Issue by ngbinh** [raquo/Laminar#48]
I am wondering how hard is it to add scala 2.13.0 support for Laminar. Now that many core libraries have supported scala 2.13.0, it would be great if Laminar follows.

**Comment by raquo** [comment]
I would like everyone who wants this done sooner to please upvote and/or comment on this issue.

So far I have not looked into 2.13 transition at all due to lack of time. PRs are welcome ([SDT for inspiration](https://github.com/raquo/scala-dom-types/pull/52/files)) with the following caveat:

If we can run the **exact same Laminar / Airstream codebase** on both 2.13 and 2.12 by means of https://github.com/scala/scala-collection-compat or some other tool, I can support both of those Scala versions at the same time. Otherwise I don't think I'll have time to maintain a separate 2.12 branch and backport all new changes to it.

Laminar makes only light use of collections so hopefully the transition itself is not hard, just need to be done. Airstream might actually take a bit more effort but that too should be doable.
