### ISSUE TITLE
Support animation events

### ISSUE THREAD

**Issue by nghuuphuoc** [raquo/Laminar#74]
The event handlers look like as following

```js
div(
  onAnimationStart --> ...,
  onAnimationonIteration --> ...,
  onAnimationEnd --> ...,
)
```

**Comment by raquo** [comment]
Hey, this is actually pretty easy. Someone would need to add these events to [MiscellaneousEventProps.scala](https://github.com/raquo/scala-dom-types/blob/258f56260869d7110c4a5a473914c3db600e503a/shared/src/main/scala/com/raquo/domtypes/generic/defs/eventProps/MiscellaneousEventProps.scala) in the Scala DOM Types project.

* Add a new `DomAnimationEvent <: DomEvent` type param to the trait
* Add four lazy vals in alphabetic order, with comments from MDN, similar to others already there

The four animation related events are listed [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement).

**Comment by nghuuphuoc** [comment]
I found the current workarounds are

1) Handle the event manually:

```js
private def handleAnimationEnd(event: AnimationEvent) = {
  ...
}

// Render
onMountCallback { ctx =>
  ctx.thisNode.ref.addEventListener[AnimationEvent]("animationend", handleAnimationEnd)
},
onUnmountCallback { ctx =>
  ctx.ref.removeEventListener[AnimationEvent]("animationend", handleAnimationEnd)
}
```

2) Follow the [Missing keys](https://laminar.dev/documentation#missing-keys) section:

```js
private val onAnimationEnd = new ReactiveEventProp[dom.AnimationEvent]("animationend")

private def handleAnimationEnd = (event: AnimationEvent) => {
  ...
}

// Render
div(
  onAnimationEnd --> handleAnimationEnd
)
```

**Comment by raquo** [comment]
Out of these, the second one is definitely better.

If anyone has the time, it would be great to add these properly to Scala DOM Types. Over time this will mean we need less and less workarounds.

**Comment by nghuuphuoc** [comment]
I am going to create the PR :+1:

**Comment by raquo** [comment]
btw, forgot to mention in case anyone does something like this.

In the example above, for `removeEventListener` to work, you need to convert your `def handleAnimationEnd` into a `val handleAnimationEnd: js.Function1[dom.AnimationEvent, Unit]`.

Otherwise, because `addEventListener` and `removeEventListener` accept `js.Function1`, this conversion from a Scala method to to `js.Function1` will happen implicitly at the two usage sites of your `handleAnimationEnd`, and each of those conversions will create a new instance of `js.Function1`. So when you call `removeEventListener`, you will be passing an instance of js.Function1 that has not been added as a listener, so nothing will happen.

Hope that makes sense. Just a small scala-js interop hiccup. When using Laminar methods (-->) you don't have to worry about this.

**Comment by nghuuphuoc** [comment]
Thank you @raquo :+1:
